course2/fancy_pc/config/routes.rb
Rails.application.routes.draw do
  resources :pcs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

course2/fancy_pc/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

course2/fancy_pc/app/models/pc.rb
class Pc < ApplicationRecord

  def self.primary_key
    puts "I'm overriding primary_key class method"
  end

  def self.hh
    puts "i'm doing hh"
  end

end

course2/fancy_pc/app/models/person.rb
class Person < ApplicationRecord
  def self.hh
    puts "hh"
  end

  def self.primary_key
    puts "or pk"
  end
end

course2/fancy_pc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

course2/fancy_pc/app/controllers/pcs_controller.rb
class PcsController < ApplicationController
  before_action :set_pc, only: [:show, :edit, :update, :destroy]

  # GET /pcs
  # GET /pcs.json
  def index
    @pcs = Pc.all
  end

  # GET /pcs/1
  # GET /pcs/1.json
  def show
  end

  # GET /pcs/new
  def new
    @pc = Pc.new
  end

  # GET /pcs/1/edit
  def edit
  end

  # POST /pcs
  # POST /pcs.json
  def create
    @pc = Pc.new(pc_params)

    respond_to do |format|
      if @pc.save
        format.html { redirect_to @pc, notice: 'Pc was successfully created.' }
        format.json { render :show, status: :created, location: @pc }
      else
        format.html { render :new }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pcs/1
  # PATCH/PUT /pcs/1.json
  def update
    respond_to do |format|
      if @pc.update(pc_params)
        format.html { redirect_to @pc, notice: 'Pc was successfully updated.' }
        format.json { render :show, status: :ok, location: @pc }
      else
        format.html { render :edit }
        format.json { render json: @pc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pcs/1
  # DELETE /pcs/1.json
  def destroy
    @pc.destroy
    respond_to do |format|
      format.html { redirect_to pcs_url, notice: 'Pc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pc
      @pc = Pc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pc_params
      params.require(:pc).permit(:cpu, :ram, :hd, :make)
    end
end

course2/fancy_pc/app/helpers/application_helper.rb
module ApplicationHelper
end

course2/fancy_pc/app/helpers/pcs_helper.rb
module PcsHelper
end

course2/fancy_pc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FancyPc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

course2/fancy_pc/app/views/pcs/_form.html.erb
<%= form_with(model: pc, local: true) do |form| %>
  <% if pc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pc.errors.count, "error") %> prohibited this pc from being saved:</h2>

      <ul>
      <% pc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cpu %>
    <%= form.text_field :cpu, id: :pc_cpu %>
  </div>

  <div class="field">
    <%= form.label :ram %>
    <%= form.text_field :ram, id: :pc_ram %>
  </div>

  <div class="field">
    <%= form.label :hd %>
    <%= form.text_field :hd, id: :pc_hd %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :pc_make %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

course2/fancy_pc/app/views/pcs/edit.html.erb
<h1>Editing Pc</h1>

<%= render 'form', pc: @pc %>

<%= link_to 'Show', @pc %> |
<%= link_to 'Back', pcs_path %>

course2/fancy_pc/app/views/pcs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pcs</h1>

<table>
  <thead>
    <tr>
      <th>Cpu</th>
      <th>Ram</th>
      <th>Hd</th>
      <th>Make</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pcs.each do |pc| %>
      <tr>
        <td><%= pc.cpu %></td>
        <td><%= pc.ram %></td>
        <td><%= pc.hd %></td>
        <td><%= pc.make %></td>
        <td><%= link_to 'Show', pc %></td>
        <td><%= link_to 'Edit', edit_pc_path(pc) %></td>
        <td><%= link_to 'Destroy', pc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pc', new_pc_path %>

course2/fancy_pc/app/views/pcs/new.html.erb
<h1>New Pc</h1>

<%= render 'form', pc: @pc %>

<%= link_to 'Back', pcs_path %>

course2/fancy_pc/app/views/pcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cpu:</strong>
  <%= @pc.cpu %>
</p>

<p>
  <strong>Ram:</strong>
  <%= @pc.ram %>
</p>

<p>
  <strong>Hd:</strong>
  <%= @pc.hd %>
</p>

<p>
  <strong>Make:</strong>
  <%= @pc.make %>
</p>

<%= link_to 'Edit', edit_pc_path(@pc) %> |
<%= link_to 'Back', pcs_path %>